spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/movie
spring.datasource.username=root
spring.datasource.password=Psa@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081